Require Capybara::DSL before using it (#154)
`SitePrism::DSL` uses `Capybara::DSL` but never requires it to be loaded.

This was never noticed since `SitePrism::DSL` was autoloaded and by
the time it was actually invoked, `capybara` was usually loaded by
some other part of the codebase.

Since 9725c54247ecf9ed7b42942e1775b2fe5d24420d `SitePrism::DSL` is
eagerloaded, resulting in

```
NameError: uninitialized constant Capybara::DSL
```

We fix this by eagerloading `Capybara::DSL` as well.